### ISSUE TITLE
Problem with meta after extending User model

### ISSUE THREAD

**Issue by Dartui** [corcel/corcel#307]
I am trying to extend `User` model (lets name it `Customer`) and I want to use meta relation. Unfourtunately, in `HasMetaField` trait there are hard-coded model classes which are mapped to meta model:
```php
private $customMetaClasses = [
    \Corcel\Model\Comment::class,
    \Corcel\Model\Term::class,
    \Corcel\Model\User::class,
];
```
Now, code like this: `Customer::find(1)->meta` gives me meta from `wp_postmeta` for post with id 1 because of fallback to `Post` class:
```php
private function getCallerClassName()
{
    $class = static::class;

    if (!in_array($class, $this->customMetaClasses)) {
        $class = Post::class;
    }

    return (new ReflectionClass($class))->getShortName();
}
```

**Comment by jgrossi** [comment]
I think this was fixed in dev branch, please take a look. If yes I'm gonna tag a new release.

**Comment by Dartui** [comment]
This is how it looks in dev: https://github.com/corcel/corcel/blob/dev/src/Traits/HasMetaFields.php#L195

I could push some tests if you want

**Comment by Dartui** [comment]
Possible solution:
```php
private function getCallerClassName()
{
    $class = static::class;

    foreach ($this->customMetaClasses as $metaClass) {
        if ($this instanceOf $metaClass) {
            return (new ReflectionClass($metaClass))->getShortName();
        }
    }

    return 'Post';
}
```

**Comment by jgrossi** [comment]
Can I close this? I think it's fixed, right?

**Comment by Dartui** [comment]
Oops, I have removed branch by mistake. AFAIK problem still occurs and need to be fixed

**Comment by jgrossi** [comment]
@Dartui, once you're contributing a lot with Corcel (and thanks for that), let's join our Trello board, what do you think? https://trello.com/b/9F9UfiOD/corcel-php
